name: Head branch workflow

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  release:
    uses: bgd-labs/github-workflows/.github/workflows/release.yml@main
  release-node:
    uses: bgd-labs/github-workflows/.github/workflows/release-node.yml@main
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
